<HBoxWidget>:
	BoxLayout:
		size: root.size
		pos: root.pos
		id: boxlayout_h
		orientation: 'horizontal'
		Button:
			text: 'h1'
			group: 'test'
		Button:
			text: 'h2'
			group: 'test'

<VBoxWidget>:
	BoxLayout:
		orientation: 'vertical'
		size: root.size
		pos: root.pos
		Button:
			text: 'v1'
			group: 'test'
		Button:
			text: 'v2'
			group: 'test'

<ContainerBox>:
	orientation: 'horizontal'
	HBoxWidget:
	VBoxWidget: